import React from "react";
import Head from "next/head";
import axios from "axios";
import Link from "next/link";
import Hero from "../components/Hero";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Listing from "../components/Listing";

export default function Home({ publishers, journals, locale }) {
  console.log(locale);
  return (
    <div>
      <Head>
        <title>Publishers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto max-w-5xl text-lg ">
        <Hero />
        <Listing publishers={publishers} journals={journals} />
      </main>
    </div>
  );
}

export async function getServerSideProps({ locale }) {
  try {
    const publisherResponse = await axios.get(
      `${process.env.BACKEND_URL}/publishers`
    );
    const journalResponse = await axios.get(
      `${process.env.BACKEND_URL}/journals`
    );
    const publishers = publisherResponse.data;
    const journals = journalResponse.data;
    return {
      props: {
        publishers,
        journals,
        locale,
        ...(await serverSideTranslations(locale, ["common", "home"])),
      },
    };
  } catch (err) {
    console.log(err);
    return {
      props: {},
    };
  }
}
